# Evaluation

- **Status:** In Progress
- **Application Document:** https://github.com/w3f/Grants-Program/blob/master/applications/dotly.md
- **Milestone:** 1
- **Kusama Identity:** Address
- **Previously successfully merged evaluation:** N/A

| Number | Deliverable | Accepted | Link | Evaluation Notes |
| ------ | ----------- | -------- | ---- |----------------- |
| **0a.** | License |<ul><li>[x] </li></ul>| [https://github.com/justmert/dotly-backend/LICENSE](https://github.com/justmert/dotly-backend/blob/master/LICENSE) - [https://github.com/justmert/dotly-frontend/LICENSE](https://github.com/justmert/dotly-frontend/blob/master/LICENSE) |  |
| **0b.** | Documentation |<ul><li>[x] </li></ul>| [https://github.com/justmert/dotly-backend/README.md](https://github.com/justmert/dotly-backend/blob/master/README.md) - [https://github.com/justmert/dotly-frontend/README.md](https://github.com/justmert/dotly-frontend/blob/master/README.md) | |
| **0c.** | Testing and Testing Guide |<ul><li>[x] </li></ul>| https://github.com/justmert/dotly-backend?tab=readme-ov-file#how-to-run-tests |  |
| **0d.** | Docker |<ul><li>[ ] </li></ul>| ----- | Not fully evaluated yet.  |
| **0e.** | Article |<ul><li>[x] </li></ul>| ---- |  |
| 1. | Search Page |<ul><li>[x] </li></ul>| https://dotly.net/ | |
| 2. | Overview Page |<ul><li>[ ] </li></ul>| https://dotly.net/overview/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m | Some problems. |
| 3. |  Overview Page - Brief Stats |<ul><li>[x] </li></ul>|  https://dotly.net/overview/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#account |  |
| 4. |  Overview Page - Parachain Balance Pie |<ul><li>[x] </li></ul>| https://dotly.net/overview/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#balance-distribution |  |
| 5. |  Overview Page - Parachain Balance List |<ul><li>[x] </li></ul>| https://dotly.net/overview/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#balance-distribution |  |
| 6. |  Overview Page - Weekly Transaction Rate |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#stats |  |
| 7. | Stats Page |<ul><li>[x] </li></ul>| https://dotly.net/stats/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m | |
| 8. |  Stats Page - Balance History |<ul><li>[x] </li></ul>| https://dotly.net/stats/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#transfer-history |  |
| 9. |  Stats Page - Transaction History |<ul><li>[x] </li></ul>| https://dotly.net/stats/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#transfer-relationship | |
| 10. |  Stats Page - Top Senders/Receivers |<ul><li>[x] </li></ul>| https://dotly.net/stats/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#transfer-relationship | |
| 11. |  Stats Page - Incoming/Outgoing Transfer Widget |<ul><li>[x] </li></ul>| https://dotly.net/stats/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#total-transfers | |
| 12. | Stats Page - Staking/Pool Reward History |<ul><li>[x] </li></ul>| https://dotly.net/rewards/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#reward-history |  |
| 13. | Extrinsics Page |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m |  |
| 14. | Extrinsics Page - Extrinsics Count History |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#activity | |
| 15. | Extrinsics Page - Extrinsics Success Rate |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#success-rate | |
| 16. | Extrinsics Page - Top Interacted Modules/Calls  |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#recent-extrinsics | |
| 17. | Extrinsics Page - Action Insight |<ul><li>[x] </li></ul>| https://dotly.net/extrinsics/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m#distribution | |
| 18. | Badges Page |<ul><li>[x] </li></ul>| https://dotly.net/badges/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m | |
| 19. | Badges Page - Badges |<ul><li>[x] </li></ul>| https://dotly.net/badges/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m | |
| 20. | Google Analytics Integration |<ul><li>[x] </li></ul>| -- |  |
| 21. | Share Feature |<ul><li>[x] </li></ul>| https://dotly.net/overview/17bR6rzVsVrzVJS1hM4dSJU43z2MUmz7ZDpPLh8y2fqVg7m | |

## Evaluation V3

### Docker

Docker is working but I received an error in the frontend. I suggest you keep the instructions to run locally without Docker in the `README`.

### Backend

I successfully ran the tests.

```
(myenv) user@localhost:~/Documents/dotly/dotly-backend$ pytest tests/*
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.1, pytest-7.3.1, pluggy-1.3.0
rootdir: /home/user/Documents/dotly/dotly-backend
configfile: pytest.ini
plugins: anyio-4.0.0
collected 49 items                                                                                                                                                                                           	 

tests/badges-test.py .....                                                                                                                                                                              	[ 10%]
tests/extrinsics-test.py ........                                                                                                                                                                       	[ 26%]
tests/badges-test.py .....                                                                                                                                                                              	[ 26%]
tests/overview-test.py ............                                                                                                                                                                     	[ 51%]
tests/rewards-test.py .............                                                                                                                                                                     	[ 77%]
tests/stats-test.py ......

=============================================================================================== 49 passed in 11.95s ===============================================================================================
```

### Frontend 

I have a problem with the frontend. I received this error. 

![image (48)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/2ddd07da-e3fa-46e8-83a0-05e8f71c9e5b)


When I refresh the page a few times, the page loads.


https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/c2d62864-84b9-453f-a117-0c3b423507f0



I didn't receive anything unexpected on the frontend log or backend log. I tested this using Docker and without Docker. I had the same result.

## Evaluation V2

### Backend

I'm having problems with the backend. The Overview page isn't loading locally, and the tests for the Overview are failing. Check the Evaluation V1 for more info about this. Could you help me with this?

### Frontend

The weekly transaction rate now returns the correct value.  

![image (47)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/56a55591-c072-48a5-a971-5250b72d3aa3)


You sent the print [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/1016#issuecomment-1745640019) of the Google Analytics working, I think the Deriverable 20 is fine.

About the Deriverable 4, I think it's better to do an amendment to change this and ajust the deriverables 6 and 8 in this amendment. If you remove a deliverable make sure to give us the dicount in the price since it was not developed. 

### Article

You said [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/1016#issuecomment-1745640019) the article in 2 days will be published. You can add the link or send it to me when you do this.

### Docker

About the Docker. Couldn't you instruct the user to create the `.env` with the information about the Firebase for the backend and the token for the frontend? Then instruct the user to build the image and launch the application.

## Evaluation V1

### Backend

Some tests for the Overview functionality failed.

<details>

```
(myenv) user@localhost:~/Documents/dotly/dotly-backend$ pytest tests/*
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.2, pytest-7.3.1, pluggy-1.3.0
rootdir: /home/user/Documents/dotly/dotly-backend
configfile: pytest.ini
plugins: anyio-3.7.1
collected 49 items                                                                                                                                                                                                

tests/badges-test.py .....                                                                                                                                                                                  [ 10%]
tests/extrinsics-test.py ........                                                                                                                                                                           [ 26%]
tests/badges-test.py .....                                                                                                                                                                                  [ 26%]
tests/overview-test.py F..F.FFFFF..                                                                                                                                                                         [ 51%]
tests/rewards-test.py .............                                                                                                                                                                         [ 77%]
tests/stats-test.py ......

==================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________________________ test_account_endpoint_valid ___________________________________________________________________________________________

    def test_account_endpoint_valid():
>       response = client.get("overview/account", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:112: in account
    data = OVERVIEW_CONTEXT.account(public_key=public_key, address=address)
widgets/overview.py:88: in account
    account = self.subscan_actor.subscan_rest_make_request("v2/scan/search", data=request_data)
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:52,515 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
_________________________________________________________________________________________ test_balance_distribution_valid _________________________________________________________________________________________

    def test_balance_distribution_valid():
>       response = client.get("overview/balance-distribution", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:172: in balance_distribution
    data = OVERVIEW_CONTEXT.balance_distribution(public_key=public_key, address=address)
widgets/overview.py:110: in balance_distribution
    balance_list = self.subscan_actor.subscan_rest_make_request("scan/multiChain/account", data=request_data)
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:53,442 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
_______________________________________________________________________________________________ test_identity_valid _______________________________________________________________________________________________

    def test_identity_valid():
>       response = client.get("overview/identity", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:224: in identity
    data = OVERVIEW_CONTEXT.identity(public_key=public_key, address=address)
widgets/overview.py:133: in identity
    multi_chain_identity = self.subscan_actor.subscan_rest_make_request(
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:54,167 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
____________________________________________________________________________________________ test_balance_distribution ____________________________________________________________________________________________

    def test_balance_distribution():
>       response = client.get("overview/balance-distribution", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:172: in balance_distribution
    data = OVERVIEW_CONTEXT.balance_distribution(public_key=public_key, address=address)
widgets/overview.py:110: in balance_distribution
    balance_list = self.subscan_actor.subscan_rest_make_request("scan/multiChain/account", data=request_data)
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:54,853 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
__________________________________________________________________________________________________ test_identity __________________________________________________________________________________________________

    def test_identity():
>       response = client.get("overview/identity", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:224: in identity
    data = OVERVIEW_CONTEXT.identity(public_key=public_key, address=address)
widgets/overview.py:133: in identity
    multi_chain_identity = self.subscan_actor.subscan_rest_make_request(
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:55,553 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
_______________________________________________________________________________________________ test_balance_stats ________________________________________________________________________________________________

    def test_balance_stats():
>       response = client.get("overview/balance-stats", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:276: in balance_stats
    data = OVERVIEW_CONTEXT.balance_stats(public_key=public_key, address=address)
widgets/overview.py:154: in balance_stats
    balance_stats = self.subscan_actor.subscan_rest_make_request(
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:56,252 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
______________________________________________________________________________________________ test_balance_history _______________________________________________________________________________________________

    def test_balance_history():
>       response = client.get("overview/balance-history", params={"public_key": PUBLIC_KEY}, headers=headers)

tests/overview-test.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
myenv/lib/python3.9/site-packages/starlette/testclient.py:488: in get
    return super().get(
myenv/lib/python3.9/site-packages/httpx/_client.py:1039: in get
    return self.request(
myenv/lib/python3.9/site-packages/starlette/testclient.py:454: in request
    return super().request(
myenv/lib/python3.9/site-packages/httpx/_client.py:815: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
myenv/lib/python3.9/site-packages/httpx/_client.py:902: in send
    response = self._send_handling_auth(
myenv/lib/python3.9/site-packages/httpx/_client.py:930: in _send_handling_auth
    response = self._send_handling_redirects(
myenv/lib/python3.9/site-packages/httpx/_client.py:967: in _send_handling_redirects
    response = self._send_single_request(request)
myenv/lib/python3.9/site-packages/httpx/_client.py:1003: in _send_single_request
    response = transport.handle_request(request)
myenv/lib/python3.9/site-packages/starlette/testclient.py:337: in handle_request
    raise exc
myenv/lib/python3.9/site-packages/starlette/testclient.py:334: in handle_request
    portal.call(self.app, scope, receive, send)
myenv/lib/python3.9/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/lib/python3.9/concurrent/futures/_base.py:440: in result
    return self.__get_result()
/usr/lib/python3.9/concurrent/futures/_base.py:389: in __get_result
    raise self._exception
myenv/lib/python3.9/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
myenv/lib/python3.9/site-packages/fastapi/applications.py:270: in __call__
    await super().__call__(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/applications.py:124: in __call__
    await self.middleware_stack(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
myenv/lib/python3.9/site-packages/starlette/middleware/cors.py:84: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:706: in __call__
    await route.handle(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
myenv/lib/python3.9/site-packages/starlette/routing.py:66: in app
    response = await func(request)
myenv/lib/python3.9/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
myenv/lib/python3.9/site-packages/fastapi/routing.py:165: in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
myenv/lib/python3.9/site-packages/starlette/concurrency.py:41: in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
myenv/lib/python3.9/site-packages/anyio/to_thread.py:33: in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:877: in run_sync_in_worker_thread
    return await future
myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:807: in run
    result = context.run(func, *args)
api/routers/overview.py:313: in balance_history
    data = OVERVIEW_CONTEXT.balance_history(public_key=public_key, address=address)
widgets/overview.py:180: in balance_history
    balance_stats = self.subscan_actor.subscan_rest_make_request(
actors/subscan_actor.py:100: in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <actors.subscan_actor.SubscanActor object at 0x7fb513b5dbb0>, retry_after = '1'

    def rate_limit_wait(
        self,
        retry_after,
    ):
>       logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
E       TypeError: unsupported operand type(s) for /: 'str' and 'int'

actors/subscan_actor.py:125: TypeError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2023-10-03 08:47:56,957 - subscan_actor.py -  [-] Rate limit exceeded.
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
WARNING  actors.subscan_actor:subscan_actor.py:94  [-] Rate limit exceeded.
============================================================================================= short test summary info =============================================================================================
FAILED tests/overview-test.py::test_account_endpoint_valid - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_balance_distribution_valid - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_identity_valid - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_balance_distribution - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_identity - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_balance_stats - TypeError: unsupported operand type(s) for /: 'str' and 'int'
FAILED tests/overview-test.py::test_balance_history - TypeError: unsupported operand type(s) for /: 'str' and 'int'
========================================================================================== 7 failed, 42 passed in 22.52s ==========================================================================================
```

</details>

### Frontend

The search address function is working. However, the front end had problems loading the info on the overview page ,for the same reason. Here is an example of the backend log when I tried to load the overview page.

<details>

```
INFO:     127.0.0.1:59396 - "GET /overview/account/?public_key=0x0507535074b7da9ae4989d5010cd0fcb3a33f8a516b721dd1a82c0a44901192e HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:59396 - "OPTIONS /overview/account?public_key=0x0507535074b7da9ae4989d5010cd0fcb3a33f8a516b721dd1a82c0a44901192e HTTP/1.1" 200 OK
2023-10-03 10:40:44,612 - subscan_actor.py - . [=] Fetching data from REST API from https://polkadot.api.subscan.io/api/v2/scan/search
2023-10-03 10:40:44,612 - subscan_actor.py - . page 1/inf of https://polkadot.api.subscan.io/api/v2/scan/search
2023-10-03 10:40:45,190 - connectionpool.py - https://polkadot.api.subscan.io:443 "POST /api/v2/scan/search HTTP/1.1" 429 50
2023-10-03 10:40:45,190 - subscan_actor.py -  [-] Rate limit exceeded.
INFO:     127.0.0.1:59396 - "GET /overview/account?public_key=0x0507535074b7da9ae4989d5010cd0fcb3a33f8a516b721dd1a82c0a44901192e HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/Documents/dotly/dotly-backend/myenv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "./api/routers/overview.py", line 112, in account
    data = OVERVIEW_CONTEXT.account(public_key=public_key, address=address)
  File "./widgets/overview.py", line 88, in account
    account = self.subscan_actor.subscan_rest_make_request("v2/scan/search", data=request_data)
  File "./actors/subscan_actor.py", line 100, in subscan_rest_make_request
    self.rate_limit_wait(retry_after)
  File "./actors/subscan_actor.py", line 125, in rate_limit_wait
    logger.warning(f". [-] Waiting for {retry_after} seconds which is {round(retry_after / 60, 2)} minutes.")
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

</details>

The other pages loaded fine. To check the Overview page, I used your hosted web site. On the Overview page, I couldn't view the Identity of an account with does have an Identity. I could checked it in the Polkadot.js.


![image (43)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/dcd48874-884b-4636-acb0-94527be358c2)


The page Rewards for some [addresses](https://dotly.net/rewards/15a9ScnYeVfQGL9HQtTn3nkUY1DTB8LzEX391yZvFRzJZ9V7) doesn't load properly. This address loads the other pages fine.

Using the hosted web site:

![image (44)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/ecae9fc3-f1f1-43dc-946c-550f88339398)

Using Locally:

![image (45)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/a7aa05b4-70e3-4606-8f77-15a616cda577)


I have some questions. 
- Where is the parachain balance pie chart? (Deliverable 4)
- Do the parachain balance list only show the other balances if the account has other tokens? 
- Could you explain why The Weekly Transaction Rate is higher than the sum of the activity in the last week? 

![image (46)](https://github.com/w3f/Grant-Milestone-Delivery/assets/112647953/8ec39d4a-e2eb-4762-a2aa-7142cd72113a)


- Why did you move the Balance History chart to the Overview page and the Transaction Rate to Extrinsics? 
- Could you send me a print of the Google Analytics?
- Do you have some sketch of the article?
